language: swift
xcode_workspace: AR Programming.xcworkspace
xcode_scheme: Pods-AR ProgrammingTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)
osx_image: xcode10.1

before_install:
- rm -rf ~/Library/Developer/Xcode/DerivedData
- brew install git-lfs
- git lfs install
- git lfs pull

jobs:
  include:
   - script: xcodebuild -workspace AR\ Programming.xcworkspace -scheme Pods-AR\ ProgrammingTests -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty
   - script: xcodebuild -workspace AR\ Programming.xcworkspace -scheme EntityComponentSystemTests -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty
   - script: xcodebuild -workspace AR\ Programming.xcworkspace -scheme ProgramModelTests -destination platform\=iOS\ Simulator,OS\=12.1,name\=iPad\ Pro\ \(9.7-inch\) build test | xcpretty
