language: swift
xcode_workspace: AR Programming.xcworkspace
xcode_scheme: Pods-AR ProgrammingTests
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPad Pro (9.7-inch)
osx_image: xcode10.1

before_install:
- rm -rf ~/Library/Developer/Xcode/DerivedData
- brew install git-lfs
- git lfs install
- git lfs pull
