language: swift
xcode_workspace: AR Programming.xcworkspace
xcode_scheme: Pods-AR ProgrammingTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
osx_image: xcode10.1

before_install:
- brew install git-lfs
- git lfs install
- echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
- git lfs pull